const questions = [
  {
    id: 1,
    question: "What is the critical difference between a trend reversal in momentum and a trend reversal in price?",
    options: [
      "A trend reversal in momentum always leads to an immediate price reversal",
      "A trend reversal in momentum is not a trend reversal in price; actual buy and sell signals can only be generated by price",
      "A trend reversal in price always precedes a momentum reversal",
      "There is no difference; they occur simultaneously"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 2,
    question: "According to the material, which of the following best describes the relationship between momentum trendline breaks and price trendline breaks?",
    options: [
      "Price trendlines break before momentum trendlines",
      "They break simultaneously",
      "Momentum tends to break its trendlines before price",
      "There is no predictable relationship"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 3,
    question: "Which THREE criteria are used to assess the significance of trendlines in momentum analysis?",
    options: [
      "Length, number of touches, and slope (steepness and direction)",
      "Volume, price action, and time frame",
      "RSI level, MACD crossover, and trading volume",
      "Fibonacci retracements, pivot points, and support levels"
    ],
    correct: 0,
    hasImage: false
  },
  {
    id: 4,
    question: "What is the principle of 'polarity' as it relates to trendlines?",
    options: [
      "Trendlines should always be drawn from left to right",
      "If a trendline previously acted as support, it might act as resistance after violation, and vice versa",
      "Positive and negative momentum must balance over time",
      "Uptrends and downtrends have equal probability"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 5,
    question: "Why might moving averages be preferred over classical trendlines in modern quantitative analysis?",
    options: [
      "Moving averages are more accurate",
      "Moving averages overcome the subjectivity of trendlines",
      "Moving averages always generate earlier signals",
      "Classical trendlines cannot be used with momentum indicators"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 6,
    question: "What is the main challenge when using momentum crossovers with moving averages?",
    options: [
      "They are too slow to generate timely signals",
      "There are many whipsaws since momentum data can be quite jagged",
      "They only work in trending markets",
      "They require advanced mathematical knowledge"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 7,
    question: "When momentum crosses over its moving average, what additional factor should be considered regarding the quality of the signal?",
    options: [
      "The trading volume at the crossover",
      "The distance from the equilibrium level where the crossover takes place",
      "The day of the week the crossover occurs",
      "The number of previous crossovers in the past month"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 8,
    question: "In the PTON example, what does it indicate when price closes above an upward sloping moving average AND momentum's MA is already sloping higher?",
    options: [
      "A weak signal suggesting caution",
      "A conflicting signal suggesting no action",
      "A good signal to open a long position or close a short position",
      "A signal to wait for further confirmation"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 9,
    question: "According to the material, overbought and oversold conditions are:",
    options: [
      "Always reliable trading signals",
      "Conditions, not signals in and of themselves",
      "Only useful in bear markets",
      "Indicators of market manipulation"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 10,
    question: "In a trading range, how should overbought and oversold signals typically be interpreted?",
    options: [
      "Overbought is bullish; oversold is bearish",
      "Both should be ignored in trading ranges",
      "When indicator falls below overbought it might be a sell signal; when it rises above oversold it might be a buy signal",
      "Only oversold conditions generate valid signals"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 11,
    question: "In uptrends, how should overbought and oversold conditions generally be interpreted?",
    options: [
      "Overbought conditions are sell signals; oversold conditions are buy signals",
      "Oversold conditions are buy signals; overbought conditions are signs of strength, not signals",
      "Both overbought and oversold should trigger immediate exits",
      "Neither condition provides meaningful information in uptrends"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 12,
    question: "In downtrends, how should overbought and oversold conditions generally be interpreted?",
    options: [
      "Overbought conditions are buy signals; oversold conditions are sell signals",
      "Both conditions signal trend reversals",
      "Overbought conditions are sell signals; oversold conditions are signs of weakness, not buy signals",
      "Only overbought conditions matter in downtrends"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 13,
    question: "In the UBER example, why was the October 2021 short signal considered particularly strong?",
    options: [
      "Because the stock had high trading volume",
      "Because RSI's six-period moving average crossed from above to below its overbought level in a downtrend, and the principle of polarity held with old support becoming new resistance",
      "Because the company announced poor earnings",
      "Because the broader market was declining"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 14,
    question: "What characteristic of downtrends is highlighted by the black boxes on RSI in the UBER chart?",
    options: [
      "Downtrends show high volatility in RSI readings",
      "Downtrends become and stay oversold without becoming overbought",
      "Downtrends always show negative divergences",
      "RSI becomes unreliable in downtrends"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 15,
    question: "What is a 'mega-overbought' condition according to Pring?",
    options: [
      "Any RSI reading above 80",
      "The initial thrust in a bull market following the final low, representing a multiyear high or even record overbought reading",
      "Three consecutive overbought readings",
      "An overbought condition lasting more than 30 days"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 16,
    question: "What typically follows a mega-overbought condition?",
    options: [
      "An immediate sharp reversal to new lows",
      "A prolonged sideways consolidation only",
      "Higher prices almost always follow after a setback or consolidation has taken place",
      "The end of the bull market"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 17,
    question: "According to the material, when is opening a long position from an overbought condition justified?",
    options: [
      "Never, as it violates basic technical analysis principles",
      "During a mega-overbought condition, but only for someone with a longer-term time horizon",
      "Any time the market is in an uptrend",
      "When volume is increasing"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 18,
    question: "In the JPMorgan (JPM) example, what followed the mega-overbought condition at point 2?",
    options: [
      "An immediate bear market",
      "A brief correction followed by continuation",
      "A three-plus-year trading range, followed by a seven-year uptrend without a 30% drop",
      "A gradual decline back to the March 2009 lows"
    ],
    correct: 2,
    hasImage: false
  },
  {
    id: 19,
    question: "What is a key characteristic of the low that precedes a mega-overbought condition?",
    options: [
      "It is usually retested within weeks",
      "It is generally not reached again for many, many years, if ever",
      "It becomes the new support level for swing trading",
      "It is always violated within the next correction"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 20,
    question: "How is a Price Oscillator (Trend Deviation) calculated?",
    options: [
      "Current price minus the low of the period",
      "(Current MA - Moving Average x periods ago) / Moving Average x periods ago * 100",
      "High minus low divided by closing price",
      "Volume-weighted average price deviation"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 21,
    question: "What is the major difference between a 1/50 price oscillator and a 50-period ROC?",
    options: [
      "The price oscillator is more accurate",
      "The price oscillator measures distance between current price and the 50-period MA; ROC measures distance between current price and price 50 periods ago",
      "ROC cannot identify divergences while price oscillator can",
      "They use different mathematical formulas for smoothing"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 22,
    question: "When using moving averages on both price and momentum, what constitutes a strong bullish signal?",
    options: [
      "Price closes above its MA while momentum's MA is declining",
      "Price closes above an upward sloping MA and momentum's MA is already sloping higher above its own MA",
      "Price is above its MA for at least 10 periods",
      "Momentum crosses above zero regardless of MA slopes"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 23,
    question: "In practical application, what challenge exists when using overbought/oversold crossovers for signal generation?",
    options: [
      "Strong uptrends rarely become oversold and strong downtrends rarely become overbought, making exits difficult to determine",
      "The signals are always too late",
      "They only work with RSI, not other indicators",
      "Volume must be analyzed simultaneously"
    ],
    correct: 0,
    hasImage: false
  },
  {
    id: 24,
    question: "What does it mean when momentum confirms price by 'shifting above zero, showing positive velocity'?",
    options: [
      "The price is moving upward at an increasing rate",
      "The rate of price change has become positive, confirming upward movement",
      "Trading volume is increasing",
      "The trend will continue indefinitely"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 25,
    question: "In the PTON example, what did the whipsaw at point 11 demonstrate?",
    options: [
      "That momentum indicators are unreliable",
      "That even good entry signals can result in short-lived trades requiring quick exits",
      "That moving averages should never be used",
      "That the entire methodology is flawed"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 26,
    question: "When momentum crosses over its moving average closer to the equilibrium level, what is the implication?",
    options: [
      "The signal is weaker and should be ignored",
      "There is a greater likelihood of a trend reversal",
      "Trading volume will increase",
      "The market is becoming less volatile"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 27,
    question: "When momentum crosses over its moving average farther from the equilibrium level, what is more likely to occur?",
    options: [
      "A strong trend reversal",
      "A consolidation of price or a counter-trend move",
      "An immediate breakdown",
      "Increased market correlation"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 28,
    question: "What was significant about the UBER RSI reaching almost 90 when price gapped above the trading range?",
    options: [
      "It was a warning sign of an imminent reversal",
      "It was a level not seen since the previous uptrend ended, representing a blast-off momentum high that preceded a multi-year rise",
      "It indicated the stock was overvalued",
      "It suggested selling pressure was building"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 29,
    question: "Why do technicians sometimes use a nine-period RSI instead of the traditional 14 periods?",
    options: [
      "It eliminates all false signals",
      "It is more sensitive and responsive to price changes, though the material doesn't specify the exact rationale",
      "It is required for mega-overbought analysis",
      "It works better with moving average crossovers"
    ],
    correct: 1,
    hasImage: false
  },
  {
    id: 30,
    question: "According to the material, what analogy best describes momentum divergence in relation to price movement?",
    options: [
      "A car accelerating while the engine temperature rises",
      "A car moving forward without pressing the gas pedal so it slows but continues (positive velocity, negative acceleration)",
      "Two cars moving at the same speed in opposite directions",
      "A car at a standstill with the engine running"
    ],
    correct: 1,
    hasImage: false
  }
];
